networks:
  tech_reference_net:
    driver: bridge
services:
  traefik:
    image: traefik:v3.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - tech_reference_net
  client:
    platform: linux/amd64
    build:
      context: ./client
      # dockerfile: Dockerfile.prod
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        NEXT_PUBLIC_SERVER_CLIENT_URL: ${NEXT_PUBLIC_SERVER_CLIENT_URL}
    environment:
      NODE_ENV: ${NODE_ENV}
      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      NEXT_PUBLIC_SERVER_CLIENT_URL: ${NEXT_PUBLIC_SERVER_CLIENT_URL}
    networks:
      - tech_reference_net
  gateway:
    platform: linux/amd64
    build:
      context: ./gateway
      dockerfile: Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.gateway.entrypoints=web"
      - "traefik.http.services.gateway.loadbalancer.server.port=8000"
    depends_on:
      - content-sync_service
      - content-api_service
      - coupon_service
      - redis
    ports:
      - "8000:8000"
    networks:
      - tech_reference_net
  content-sync_service:
    platform: linux/amd64
    build:
      context: ./services/content-sync_service
      dockerfile: Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV}
      NOTION_TOKEN: ${NOTION_TOKEN}
      NOTION_COMMAND_DATABASE_ID: ${NOTION_COMMAND_DATABASE_ID}
      NOTION_STARTER_DATABASE_ID: ${NOTION_STARTER_DATABASE_ID}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      SUPABASE_ROLE_KEY: ${SUPABASE_ROLE_KEY}
    labels:
      - "traefik.enable=false"
    depends_on:
      - redis
    networks:
      - tech_reference_net
  content-api_service:
    platform: linux/amd64
    build:
      context: ./services/content-api_service
      dockerfile: Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      SUPABASE_ROLE_KEY: ${SUPABASE_ROLE_KEY}
    labels:
      - "traefik.enable=false"
    depends_on:
      - redis
    networks:
      - tech_reference_net
  coupon_service:
    platform: linux/amd64
    build:
      context: ./services/coupon_service
      dockerfile: Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ROLE_KEY: ${SUPABASE_ROLE_KEY}
    labels:
      - "traefik.enable=false"
    depends_on:
      - redis
    networks:
      - tech_reference_net
  redis:
    image: redis:7.2
    labels:
      - "traefik.enable=false"
    networks:
      - tech_reference_net
    # ports:
    #   - "6379:6379"
