services:
  traefik:
    image: traefik:v3.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  client:
    platform: linux/amd64
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
  gateway:
    platform: linux/amd64
    build:
      context: ./gateway
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.gateway.entrypoints=web"
      - "traefik.http.services.gateway.loadbalancer.server.port=8000"
    depends_on:
      - content-sync_service
      - content-api_service
      - coupon_service
      - redis
    ports:
      - "8000:8000"
  content-sync_service:
    platform: linux/amd64
    build:
      context: ./services/content-sync_service
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
    labels:
      - "traefik.enable=false"
    depends_on:
      - redis
  content-api_service:
    platform: linux/amd64
    build:
      context: ./services/content-api_service
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
    labels:
      - "traefik.enable=false"
    depends_on:
      - redis
  coupon_service:
    platform: linux/amd64
    build:
      context: ./services/coupon_service
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
    labels:
      - "traefik.enable=false"
    depends_on:
      - redis
  redis:
    image: redis:7.2
    labels:
      - "traefik.enable=false"
    # ports:
    #   - "6379:6379"
