FROM node:20.16.0-alpine As builder
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

RUN npm run build

FROM node:20.16.0-alpine
WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

COPY --from=builder /app/dist ./dist
COPY scripts/healthcheck.js ./scripts/healthcheck.js

CMD ["node", "dist/server.js"]